[[redirects]]
  from = "/*"
  to = "/"
  status = 200
  
[[redirects]]
from = "/docs"
to = "/"

[[redirects]]
  from = "/docs/nextevent"
  to = "/"

[[redirects]]
  from = "/allevents"
  to = "/k"

[[redirects]]
  from = "/allusers"
  to = "https://goeventapiservice.netlify.app/docs/allusers"

[[redirects]]
  from = "/accessdenied"
  to = "/"

