
[[redirects]]
from = "/docs"
to = "/"

[[redirects]]
  from = "/docs/nextevent"
  to = "/docs/nextevent"

[[redirects]]
  from = "/allevents"
  to = "/k"

[[redirects]]
  from = "/allusers"
  to = "/"


[[redirects]]
  from = "/accessdenied"
  to = "/"

